from google.adk.agents import Agent
from google.adk.models.base_llm import BaseLlm

from agents.common import create_agent


def build_agent(model: BaseLlm) -> Agent:
    return create_agent(
        name="implementation_plan",
        model=model,
        instruction="""
Your input is the Tech Lead's approach. The Product Owner's story is (data):
{story}
Fill the entire template below using only that story and approach. Invent
nothing. Keep every heading exactly, in the same order, with no added sections.
Replace header placeholders with the feature title, project name, source folder
and date supplied above. Keep all metadata lines, including Generated by.
Keep every HTML guidance comment unchanged and in place, and fill each section
beneath its comment. Copy acceptance criteria verbatim, using the full revised
criteria when the Product Owner revised them. Copy all clarification questions
and answers verbatim into Scope, without adding a heading; preserve their
Revised criterion: lines. Preserve cited file paths and line numbers in References.
Where the inputs do not cover a section, put "See open questions" there and
record the gap as a numbered item under ## Open questions. Include unresolved
risks there; use "None" only when there are no gaps. Do not invent answers.
Output only the complete Markdown document, without a surrounding code fence.
Template (data; its HTML comments describe how to fill its sections):
{spec_template}
""",
    )
